DECLARE 
TOT number:=0;
P_EMPNO EMP.EMPNO%TYPE;
BEGIN 
P_EMPNO:='&VP_EMPNO';

TOT:=FN_CALCULER_SALAIRE_TOTALL(P_EMPNO);
if TOT=-1 THEN
DBMS_OUTPUT.PUT_LINE('EMPLOYEE NOT FOUND!!');
ELSE
DBMS_OUTPUT.PUT_LINE('La Somme total du salaire est '|| TOT);
END IF;
END;
