CREATE TABLE TABLE1 
(
  CIN NUMBER(20) NOT NULL 
, NUM_RESERVATION VARCHAR2(20) NOT NULL 
, NUM_CHAMBRE VARCHAR2(5) NOT NULL 
, STATUT_RESERVATION VARCHAR2(7) NOT NULL 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    CIN 
  , NUM_RESERVATION 
  , NUM_CHAMBRE 
  , STATUT_RESERVATION 
  )
  ENABLE 
);
