CREATE TABLE CLIENT 
(
  CIN NUMBER(14, 0) NOT NULL 
, NOM VARCHAR2(20 BYTE) NOT NULL 
, PRENOM VARCHAR2(20 BYTE) NOT NULL 
, NUMERO_TELEPHONE NUMBER(15, 0) NOT NULL 
, EMAIL VARCHAR2(20 BYTE) 
, CONSTRAINT CLIENT_PK PRIMARY KEY 
  (
    CIN 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX CLIENT_PK ON CLIENT (CIN ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
