CREATE TABLE CLIENT 
(
  CIN NUMBER(20) NOT NULL ,
  NOM VARCHAR2(15) NOT NULL ,
  PRENOM VARCHAR2(15) NOT NULL ,
  TELEPHONE NUMBER(20) NOT NULL ,
  EMAIL VARCHAR2(30) ,
  CONSTRAINT CLIENT_PK PRIMARY KEY (CIN)
);

CREATE TABLE RESERVATION 
(
  NUM_RESERVATION VARCHAR2(20) NOT NULL ,
  DATE_DEBUT DATE ,
  DATE_FIN DATE ,
  NUM_CHAMBRE VARCHAR2(5) NOT NULL ,
  MONTANT NUMBER ,
  STATUT_RESERVATION VARCHAR2(7) NOT NULL ,
  CONSTRAINT RESERVATION_PK PRIMARY KEY (NUM_RESERVATION , NUM_CHAMBRE , STATUT_RESERVATION ) 
);

CREATE TABLE EFFECTER 
(
  CIN NUMBER(20) NOT NULL ,
  NUM_RESERVATION VARCHAR2(20) NOT NULL ,
  NUM_CHAMBRE VARCHAR2(5) NOT NULL ,
  STATUT_RESERVATION VARCHAR2(7) NOT NULL ,
  CONSTRAINT EFFECTER_PK PRIMARY KEY(CIN , NUM_RESERVATION , NUM_CHAMBRE , STATUT_RESERVATION )
);

ALTER TABLE EFFECTER ADD CONSTRAINT FK_1 FOREIGN KEY(CIN) REFERENCES CLIENT(CIN);
ALTER TABLE EFFECTER ADD CONSTRAINT FK_2 FOREIGN KEY(NUM_RESERVATION, NUM_CHAMBRE, STATUT_RESERVATION) REFERENCES RESERVATION(NUM_RESERVATION, NUM_CHAMBRE, STATUT_RESERVATION);
CREATE TABLE CHAMBRE_1
(
  NUM_CHAMBRE VARCHAR2(5) NOT NULL ,
  TYPE_ VARCHAR2(10) ,
  TARIF_NUIT NUMBER(10) ,
  STATUT_CHAMBRE VARCHAR2(10) NOT NULL ,
  CONSTRAINT CHAMBRE_PK1 PRIMARY KEY (NUM_CHAMBRE , STATUT_CHAMBRE ) 
);
ALTER TABLE RESERVATION ADD CONSTRAINT FK_3 FOREIGN KEY(NUM_CHAMBRE, STATUT_RESERVATION) REFERENCES CHAMBRE_1(NUM_CHAMBRE, STATUT_CHAMBRE);
ALTER TABLE CHAMBRE_1 ADD NUM_RESERVATION VARCHAR2(20) NOT NULL;
ALTER TABLE CHAMBRE_1 ADD CONSTRAINT FK_5 FOREIGN KEY(NUM_RESERVATION, NUM_CHAMBRE, STATUT_RESERVATION) REFERENCES RESERVATION(NUM_RESERVATION, NUM_CHAMBRE, STATUT_RESERVATION);
ALTER TABLE CHAMBRE_1 ADD STATUT_RESERVATION VARCHAR2(7) NOT NULL;
CREATE TABLE CONSERNER (
  NUM_CHAMBRE VARCHAR2(10) NOT NULL ,
  STATUT_CHAMBRE VARCHAR2(10) NOT NULL ,
  NUM_RESERVATION VARCHAR2(20) NOT NULL ,
  STATUT_RESERVATION VARCHAR2(7) NOT NULL ,
  CONSTRAINT CONSERNER_PK PRIMARY KEY (NUM_CHAMBRE , STATUT_CHAMBRE , NUM_RESERVATION , STATUT_RESERVATION ) ,
  CONSTRAINT FC_1 FOREIGN KEY(NUM_RESERVATION, STATUT_RESERVATION, NUM_CHAMBRE) REFERENCES RESERVATION(NUM_RESERVATION, STATUT_RESERVATION, NUM_CHAMBRE),
);
CREATE TABLE EMPLOYE 
(NUM_E VARCHAR2(15) NOT NULL ,
NOM_E VARCHAR2(20) NOT NULL ,
PRENOM_E VARCHAR2(20) NOT NULL ,
POSTE VARCHAR2(10) NOT NULL ,
TELEPHONE NUMBER NOT NULL ,
SALAIRE NUMBER ,
ADRESSE_E VARCHAR2(20) NOT NULL ,
DATE_EMBAUCHE DATE ,
CONSTRAINT EMPLOYE_PK PRIMARY KEY (NUM_E, POSTE)
);
CREATE TABLE GERER (
  NUM_CHAMBRE VARCHAR2(10) NOT NULL ,
  STATUT_CHAMBRE VARCHAR2(10) NOT NULL ,
  NUM_E VARCHAR2(15) NOT NULL ,
  POSTE VARCHAR2(10) NOT NULL ,
  CONSTRAINT GERER_PK PRIMARY KEY (NUM_E, POSTE, NUM_CHAMBRE, STATUT_CHAMBRE),
  CONSTRAINT GERER_FK1 FOREIGN KEY(STATUT_CHAMBRE, NUM_CHAMBRE) REFERENCES CHAMBRE_1(STATUT_CHAMBRE, NUM_CHAMBRE),
  CONSTRAINT GERER_FK2 FOREIGN KEY (NUM_E, POSTE) REFERENCES EMPLOYE(NUM_E, POSTE)
);
CREATE TABLE FACTURE 
(NUM_FACTURE VARCHAR2(15) NOT NULL ,
DATE_FACTURE DATE NOT NULL ,
MONTANT NUMBER NOT NULL ,
SERVICE_FACURE VARCHAR2(15) ,
CONSTRAINT FACTURE_PK PRIMARY KEY(NUM_FACTURE,DATE_FACTURE)
);
ALTER TABLE RESERVATION 
ADD NUM_FACTURE VARCHAR2(15) NOT NULL;

ALTER TABLE RESERVATION 
ADD DATE_FACTURE DATE NOT NULL;

ALTER TABLE RESERVATION 
ADD CONSTRAINT AR FOREIGN KEY(NUM_FACTURE, DATE_FACTURE) 
REFERENCES FACTURE(NUM_FACTURE, DATE_FACTURE);

CREATE TABLE ENGENDRE (
  NUM_RESERVATION VARCHAR2(20) NOT NULL ,
  STATUT_RESERVATION VARCHAR2(7) NOT NULL ,
  NUM_FACTURE VARCHAR2(15) NOT NULL ,
  DATE_FACTURE DATE NOT NULL ,
  NUM_CHAMBRE VARCHAR2(5) NOT NULL ,
  CONSTRAINT ENG_PK PRIMARY KEY(NUM_RESERVATION, STATUT_RESERVATION, NUM_FACTURE, DATE_FACTURE, NUM_CHAMBRE),
  CONSTRAINT FC_ENG FOREIGN KEY(NUM_RESERVATION, STATUT_RESERVATION, NUM_CHAMBRE) REFERENCES RESERVATION(NUM_RESERVATION, STATUT_RESERVATION, NUM_CHAMBRE),
  CONSTRAINT FG_ENG FOREIGN KEY(NUM_FACTURE, DATE_FACTURE) REFERENCES FACTURE(NUM_FACTURE, DATE_FACTURE)
);



